# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weibo

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'KILabel'

  target 'WeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
